### ISSUE TITLE
Lines with no length do not draw in the world

### ISSUE THREAD

**Issue by dmurfet** [metauni/metaboard#18] opened 2021-12-27 02:01 UTC
On a `v0.3.0` metaboard, use a mouse to single click on the board (choose a larger pen size). It will draw a solid circle in the canvas, but nothing is visible in the world (as the part probably has length zero).

**Comment by billy-price** [comment] 2021-12-28 09:11
This is caused by the same thing as #13. Fixed in [v0.3.2](https://github.com/metauni/metaboard/releases/tag/v0.3.2)

**Closed by billy-price** 2021-12-28 09:11 UTC
